packages:
  - 'apps/*'
  - 'packages/*'

# "onlyBuiltDependencies":
#   - "esbuild"

# overrides:
#   "zod": "^4.4.3"

allowBuilds:
  '@credenza3/passport-evm': false
  '@nestjs/core': false
  '@parcel/watcher': false
  esbuild: true
  lefthook: true
  unrs-resolver: false

minimumReleaseAge: 0
